### ISSUE TITLE
Unable to Edit a Task

### ISSUE THREAD

**Issue by marcelomichelsohn** [h-be/acorn#12]
I've created a task and tried to add a timeframe. I can see the calendar, I can choose the start and finish date but it doesn't save it to the task. The same with priority. I can't save my vote.

**Comment by marcelomichelsohn** [comment]
It is working now.

**Comment by Connoropolous** [comment]
I have seen instances where the very first time taking a new action it can be very slow to respond, and we do not have the best indicators yet about whether your response is 'pending'. Future times making the same API call can be much faster. This may explain the behaviour you saw. We can and will look into it.
