### ISSUE TITLE
Error from npm run dna-pack

### ISSUE THREAD

**Issue by pmoc2001** [h-be/acorn#15]
Hi,

Get this error on Ubuntu.

> acorn@0.5.1-alpha dna-pack /home/casper/acorn
> . scripts/dna-pack.sh

   Compiling byteorder v1.4.3
   Compiling lazy_static v1.4.0
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `lazy_static`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: build failed
sh: 5: scripts/dna-pack.sh: hc: not found
sh: 6: scripts/dna-pack.sh: hc: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! acorn@0.5.1-alpha dna-pack: `. scripts/dna-pack.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the acorn@0.5.1-alpha dna-pack script.

**Comment by Connoropolous** [comment]
Hi @pmoc2001 

You would first need to run the script: install-hc-tools.sh which you can do via an `npm` command from the root folder... `npm run dna-install-deps`

Then you also need to run

```bash
rustup target install wasm32-unknown-unknown
```

which installs the "webassembly" compilation target for Rust, which we need. I forgot to document that particular command.

**Comment by Connoropolous** [comment]
What is your goal in trying to run the code, by the way? If I know that I can help you better.

**Comment by pmoc2001** [comment]
Hi,

I just wanted to see if it worked and view app on local machine. I followed
the readme.

Thanks,

Casper

**Comment by pmoc2001** [comment]
Hi thanks for getting back to me.

I'll give it a try. Thank you and for your efforts building the app.

Casper
