### ISSUE TITLE
update and align copyrights and license

### ISSUE THREAD

**Issue by samcooley** [h-be/acorn#17]
Copyrights at this point should be:
"© 2020-2021 Harris-Braun Enterprises, LLC"
and licences declared as:
“Licensed under the Cryptographic Autonomy License version 1.0,"  (per https://github.com/holochain/cryptographic-autonomy-license)

This applies to at least:
- web/dist/splashscreen.html
- electron/package.json

**Comment by samcooley** [comment]
In package.json I also believe the appId should be changed to:
    "appId": "com.harris-braun.acorn",
(i.e. drop the enterprises in the domain name)

**Comment by pegahvaezi** [comment]
updates done
