### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by felri** [h-be/acorn#23]
Pretty much the title, just curious because I love this project.

**Comment by Connoropolous** [comment]
@felri Hi! Yes indeed it is. Development has continued apace this summer, though we've not been as consistent in communications as we could have been, while in that mode. 

Basically, a release is extremely near, within a week we shall be releasing and bringing some huge improvements and features :)

**Comment by Connoropolous** [comment]
Hey @felri we have a new release, v0.5.2-alpha https://github.com/h-be/acorn/releases/tag/v0.5.2-alpha

**Comment by pegahvaezi** [comment]
The acorn project is definitely active :) We will be in communication via email soon with a summary of the recent updates.
