### ISSUE TITLE
write a test for projects -> init

### ISSUE THREAD

**Issue by Connoropolous** [h-be/acorn#29]
This one should be easier than others to start, which I am basing off of the notion of 'total HDK function calls'

First, add `pub` to it so you can reference it outside the crate, in the tests folder. 
Create a new test file that corresponds to this `lib.rs` file, over in `tests` crate folder.
Writing the test will require drilling into the two function calls, then looking for calls to the HDK that will need to be mocked

https://github.com/h-be/acorn/blob/7fab3552fad60036eca4dd8f8d5b2aebbdd45139/dna/zomes/projects/src/lib.rs#L17-L27

**Comment by WFinck97** [comment]
@Connoropolous, I've hit a bit of a roadblock, whenever I try to run a test (even if it's one you've already written), I get the following error:
```
error[E0658]: use of unstable library feature 'duration_constants'
   --> /home/wesley/.cargo/registry/src/github.com-1ecc6299db9ec823/kitsune_p2p-0.0.3/src/gossip/sharded_gossip.rs:377:41
    |
377 |         const START_OF_TIME: Duration = Duration::MAX;
    |                                         ^^^^^^^^^^^^^
    |
    = note: see issue #57391 <https://github.com/rust-lang/rust/issues/57391> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `kitsune_p2p`
```

Am I working with the wrong version of the code?

**Comment by WFinck97** [comment]
I ran `rustc --explain E0658` and it seems like one solution is to switch to a nightly version of rustc. Have you encountered this problem before with compiling kitsune_p2p, and what is your workaround?

**Comment by Connoropolous** [comment]
Hm, more likely a version  of rust required. Run `rustc --version`

**Comment by WFinck97** [comment]
rustc 1.51.0 (2fd73fabe 2021-03-23)

**Comment by WFinck97** [comment]
okay I just updated an now have:
`rustc 1.54.0 (a178d0322 2021-07-26)`
Will retry the tests

**Comment by Connoropolous** [comment]
Yes the 1.54 seems a lot better

**Comment by WFinck97** [comment]
cool, that seemed to have fixed the issue!

**Comment by Connoropolous** [comment]
I'll put a bit of context on it... Rust previews new "features" of Rust language on whats called their 'nightly' channel

`use of unstable library feature 'duration_constants'`

usually this nightly has things they'd call 'unstable' because they're still subject to changes in how they work. 

Eventually features can move from being released on the nightly channels, into the 'stable' channel, that we are using. 

So back at 1.51 that you were on the feature was considered unstable, but by version 1.54 the feature has been stabilized and released somewhere in between versions 1.51 and 1.54

**Comment by WFinck97** [comment]
ah okay that makes sense

**Comment by Connoropolous** [comment]
carrying on ok now? posting up with your blocker was perfect, do that again if there's a bug-like thing can't be solved after say... 15 minutes of trying

**Comment by WFinck97** [comment]
will do!
