### ISSUE TITLE
v0.5.4-alpha next steps

### ISSUE THREAD

**Issue by Connoropolous** [h-be/acorn#38]
- [x] @Connoropolous verify that export/import from last version is working
- [x] re-enable unit tests Actions workflow
- [x] re-enable dna build steps (which add compile time to the release automation)
- [x] modify the 'datastore' configurations to use a proper version number (`databases-0-5-4-alpha`)
- [x] de-hardcode the "test-release" name and replace with the proper tag version (referencing these: https://github.com/Sprillow/holochain-runner/blob/4ddea47865e2f19f495c59485b5573cbe15c1b51/.github/workflows/release.yml#L56 )
- [x] disable the release flow from happening on every push, and re-enable it only running during a tag
- [x] re-enable the 'create release' stage of the release workflow

Other stuff
- [x] figure out what's wrong with networking
- [ ] #46
- [x] #49
- [ ] #48

**Comment by WFinck97** [comment]
Here are some issues I ran into while testing out the app on all 3 OSs:
- creating a new goal doesn't automatically update the state on another device (have to refresh) whereas goal status, and comments, and other features of a goal update immediately
- when typing in the title of a newly created goal, if you click the cursor anywhere outside of the text before pressing `enter`, a duplicate goal is created
- if there is more than 1 top priority goal, they don't show up in the priority list
<img width="379" alt="image" src="https://user-images.githubusercontent.com/39413655/135690450-681208bf-f17f-4b0b-867d-db1a7baa80b7.png">
<img width="427" alt="image" src="https://user-images.githubusercontent.com/39413655/135690477-4808ca96-25ec-4a61-aabc-5a71978ad90c.png">
- not able to expand a goal from the top priority list
- I somehow managed to create an invisible goal (created on mac, not visible on linux)
<img width="371" alt="image" src="https://user-images.githubusercontent.com/39413655/135690666-4437087c-7ca2-490b-ba46-2f415e256021.png">
<img width="278" alt="image" src="https://user-images.githubusercontent.com/39413655/135690678-2b5276fb-f3af-41f3-89d8-3a5604022852.png">
- the first project (which was populated with a lot of goals on mac and linux) was stuck syncing for a long time (it never synced fully after a few minutes before shutting down

**Comment by Connoropolous** [comment]
nice sleuthing, good stuff.

**Comment by Connoropolous** [comment]
<img width="923" alt="Screen Shot 2021-10-01 at 4 22 13 PM" src="https://user-images.githubusercontent.com/1409121/135695415-be55b534-c2fc-49cd-89ea-0342f2891be3.png">

I see this in the console in relation to the empty priority list
