### ISSUE TITLE
App crashes when you press Delete to archive a card while also having the "edge connector" attached to it

### ISSUE THREAD

**Issue by felri** [h-be/acorn#5]
You can reproduce this error like this: https://i.imgur.com/enfi4wX.mp4

**Comment by Connoropolous** [comment]
Thanks for the screen cap! We will investigate

**Comment by Connoropolous** [comment]
@felri 

I've tried to reproduce this error, but can't seem to. Can you try a few times to replicate and see if you can reliably do so? has this issue occurred in any way since you first found it?

**Comment by Connoropolous** [comment]
Oh sorry, I didn't understand how the video related to the screencap. 

I've now been able to reproduce because I realize you meant pressing a keyboard button 'Delete'. 

Having a selected card is fine, but having an "edge connector" in progress is not fine.

Working on a fix

**Comment by Connoropolous** [comment]
We fixed this as well, by disabling the 'delete' key while a new goal is in the process of being created
