### ISSUE TITLE
Hierarchy and Timeframe can't be edited initially after new goal creation in "Expanded View Mode"

### ISSUE THREAD

**Issue by felri** [h-be/acorn#6]
Video: https://i.imgur.com/fwdxeGo.mp4

I'm trying to click but nothing happens, this one just seems that I need to do something before I'm able to set the type

**Comment by Connoropolous** [comment]
I will double check that function. Can you try using the 'quick edit' version to change, instead of the 'expanded view? 

Quick edit is the pencil icon when you hover over a goal

**Comment by Connoropolous** [comment]
Yes, this was a very real issue, thanks for reporting!

On the very first time that you go to edit Timeframe or Hierarchy through the "Expanded View Mode" it failed to update the Goal. 

Fix is coming.
