### ISSUE TITLE
Unable to Delete Cards

### ISSUE THREAD

**Issue by adamth0mps0n** [h-be/acorn#61]
Selecting a card and hitting the delete key does not work on my Arch Linux Distro. 
Please let me know if there is another way to delete cards

**Comment by adamth0mps0n** [comment]
I found the archive icon.. But the delete key shortcut does not work

**Comment by Connoropolous** [comment]
I see. Ok thankyou for noting the linux system, that is prbly the important detail.

**Comment by adamth0mps0n** [comment]
Never mind. The backspace key worked just fine to delete cards and connectors. 
I am loving Acorn by the way. Its been very handy, even with the present features.

**Comment by adamth0mps0n** [comment]
So either  the doco needs to be updated to reference the backspace key instead of the Delete key, or the app needs to be modified to use the Delete key instead of the Backspace key

**Comment by Connoropolous** [comment]
that's great to hear on all accounts! Have you worked solo on a project, or collaboratively?

**Comment by adamth0mps0n** [comment]
Working collaboratively.

One project has 5 active members.

Sometimes team members have problems joining the project, but a few clean
install attempts seems to fix things. Also we often have to refresh to get
the latest changes, but overall it's quite good.
Adam

**Comment by Connoropolous** [comment]
Thats great to hear. Would it be alright with you if we contacted you sometime to ask you some questions about that?

**Comment by adamth0mps0n** [comment]
Sure.
I will do all I can to help get this app running..
Cheers
Adam
