### ISSUE TITLE
SQLLite error connecting with the latest Acorn

### ISSUE THREAD

**Issue by adamth0mps0n** [h-be/acorn#64]
I have installed v0.56 Alpha2 and upon execution I get the following from my terminal. 
--------------------------------------------------------------------------------------------------------------

(acorn:4573): Gtk-WARNING **: 11:38:18.292: Theme parsing error: gtk.css:5822:26: '-shadow' is not a valid color name

(acorn:4573): Gtk-WARNING **: 11:38:18.295: Theme parsing error: gtk.css:5825:14: not a number

(acorn:4573): Gtk-WARNING **: 11:38:18.295: Theme parsing error: gtk.css:5826:13: not a number

(acorn:4573): Gtk-WARNING **: 11:38:18.295: Theme parsing error: gtk.css:5827:11: Expected a length
Gtk-Message: 11:38:18.330: Failed to load module "appmenu-gtk-module"

(acorn:4573): LIBDBUSMENU-GLIB-WARNING **: 11:38:20.661: About to Show called on an item wihtout submenus.  We're ignoring it.

(acorn:4573): LIBDBUSMENU-GLIB-WARNING **: 11:38:20.681: About to Show called on an item wihtout submenus.  We're ignoring it.

(acorn:4573): LIBDBUSMENU-GLIB-WARNING **: 11:38:20.731: About to Show called on an item wihtout submenus.  We're ignoring it.

(acorn:4573): LIBDBUSMENU-GLIB-WARNING **: 11:38:23.495: About to Show called on an item wihtout submenus.  We're ignoring it.

(acorn:4573): LIBDBUSMENU-GLIB-WARNING **: 11:38:23.495: About to Show called on an item wihtout submenus.  We're ignoring it.

(acorn:4573): LIBDBUSMENU-GLIB-WARNING **: 11:38:23.585: About to Show called on an item wihtout submenus.  We're ignoring it.
Dec 07 11:38:39.744 ERROR holochain_sqlite::db: Connection pool took 24.740732ms to be free'd
---------------------------------------------------------------------------------------------------------------
Acorn will open but with a forced refresh but only with local data. 
I am not worried about the Gtk warning's as I am running KDE and not gnome. I could install the said libraries and see if it changes anything. 

The other annoying thing is that Acorn process's run at the Kernel level and are impossible to kill. A reboot is the only option.

**Comment by Connoropolous** [comment]
That error is an overstatement and can be ignored. It should technically be a warning level log not an error

**Comment by Connoropolous** [comment]
But thats coming from Holochain itself

**Comment by adamth0mps0n** [comment]
The last error "Dec 07 11:38:39.744 ERROR holochain_sqlite::db: Connection pool took 24.740732ms to be free'd" prevents acorn form loading. It just sits there with an acorn spinning.. If I force reload I can get  local copy only.

**Comment by adamth0mps0n** [comment]
Latest ACORN 0.5.7 resolves this issue.. Closing it now.
