### ISSUE TITLE
Task Boxes not rendering - drawimage error. v0.5.9-alpha

### ISSUE THREAD

**Issue by adamth0mps0n** [h-be/acorn#72]
One project does not render the boxes. I have lines connecting empty spaces. 
All my other projects work fine. I have tried to re-import from a few different .JSON files but with the same result. 
Probably not related but there are a lot of errors associated with Acorn calling the file --> "  file:///tmp/.mount_Acorn-acXEOP/resources/app.asar/web/main.js:351:295448  "  

See error below.
Dump stack is below.. 
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.

Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at file:///tmp/.mount_Acorn-O77SOB/resources/app.asar/web/main.js:351:295448
    at Array.forEach (<anonymous>)
    at Fs (file:///tmp/.mount_Acorn-O77SOB/resources/app.asar/web/main.js:351:294674)
    at file:///tmp/.mount_Acorn-O77SOB/resources/app.asar/web/main.js:351:298698
    at Array.forEach (<anonymous>)
    at Gs (file:///tmp/.mount_Acorn-O77SOB/resources/app.asar/web/main.js:351:298503)
    at file:///tmp/.mount_Acorn-O77SOB/resources/app.asar/web/main.js:359:87919
    at cs (file:///tmp/.mount_Acorn-O77SOB/resources/app.asar/web/main.js:309:83260)
    at Tl (file:///tmp/.mount_Acorn-O77SOB/resources/app.asar/web/main.js:309:102452)
    at t.unstable_runWithPriority (file:///tmp/.mount_Acorn-O77SOB/resources/app.asar/web/main.js:317:3844)

**Comment by Connoropolous** [comment]
were you operating offline at the time? we've had some issues that crop up related to using a profile image, but then being offline and not being able to access it. We'd like to implement local first profile pics soon

**Comment by adamth0mps0n** [comment]
No I was online at the time.

**Comment by Connoropolous** [comment]
K, I see.

**Comment by adamth0mps0n** [comment]
I have noticed that opening this project in V5.7 results in the same issue, and importing into version 6.0 is also the same.. 
Its most likely a corrupt .JSON file, so I am closing this..

**Comment by adamth0mps0n** [comment]
I have noticed that opening this project in V5.7 results in the same issue, and importing into version 6.0 is also the same.. 
Its most likely a corrupt .JSON file, so I am closing this..
